name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Ubuntu 22.04 satisfies the gtk4 version baseline (4.6 > 4.4)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          target
        key: cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev
    - name: Compile
      run: |
        mkdir -p ~/.cargo/{git,registry}
        cargo build --release
        mv target/release/showimg showimg-amd64

    - name: Deploy - Create and Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          showimg-amd64
    - name: Deploy - Put it in artifact (if not a tag)
      if: false == startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: showimg
        path: |
          showimg-amd64
