name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Ubuntu 22.04 satisfies the gtk4 version baseline (4.6 > 4.4)
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          target
        key: cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev
    - name: Compile
      run: |
        mkdir -p ~/.cargo/{git,registry}
        cargo build --release
        mv target/release/showimg showimg-amd64
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: showimg-amd64
        path: showimg-amd64

  build-flatpak-and-release:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: showimg-amd64
        path: ./
    
    - name: Build Flatpak Package
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: moe.taoky.showimg.flatpak
        manifest-path: build-aux/moe.taoky.showimg.yaml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Set Release Version
      if: startsWith(github.ref, 'refs/tags/')
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./showimg-amd64
          ./moe.taoky.showimg.flatpak
